"""
AgroGuard Backend - ChatMessage Model

Defines the SQLAlchemy ORM model for the ``chat_messages`` table in
PostgreSQL (Supabase).

Table: chat_messages

Architecture reference: Architecture.md §6 — Database Design,
                        §9 — AI Architecture
PRD reference:          PRD.md §7 F3 — AI Agricultural Assistant

Message flow (Architecture.md §9):

    User sends a message  →  stored as role=USER
    Gemini API responds   →  stored as role=ASSISTANT

Design decisions:
    * ``session_id`` is a **non-nullable** FK to ``chat_sessions.id`` with
      ``ondelete="CASCADE"``.  A message without its parent session has no
      context or ownership — cascading keeps the DB consistent automatically
      when a session is deleted (e.g. after expiry or account deletion).

    * ``role`` uses a Python ``MessageRole`` enum (USER / ASSISTANT) stored
      as ``VARCHAR(10)``.  This follows the same pattern as ``selected_plan``
      on Scan — a new Postgres ENUM type would risk DDL conflicts.
      ``VARCHAR`` with application-layer validation is safer and still
      type-checked in Python.

    * ``message`` (TEXT) holds the raw message content.  No length cap is
      applied at the DB layer because Gemini responses can be arbitrarily
      long; length constraints, if needed, belong in the Pydantic schema
      validation layer.

    * ``created_at`` is non-nullable with ``server_default=now()``.  Messages
      are immutable once stored — there is no ``updated_at`` column because
      editing chat history would violate the integrity of the conversation
      and is not a PRD feature.  ``ChatSession.messages`` is already ordered
      by ``ChatMessage.created_at``, so this column drives chronological
      ordering of the conversation.

    * ``session_id`` is indexed for fast message look-ups by session, which
      is the primary access pattern (fetch all messages for a session).

Usage:
    from app.models.chat_message import ChatMessage, MessageRole

    user_msg = ChatMessage(
        session_id=session.id,
        role=MessageRole.USER,
        message="What causes Early Blight in tomatoes?",
    )

    ai_msg = ChatMessage(
        session_id=session.id,
        role=MessageRole.ASSISTANT,
        message="Early Blight is caused by the fungus Alternaria solani...",
    )
"""

from __future__ import annotations

import enum
import uuid
from typing import TYPE_CHECKING

from sqlalchemy import ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql.sqltypes import DateTime

from app.database import db

if TYPE_CHECKING:
    from app.models.chat_session import ChatSession


# ---------------------------------------------------------------------------
# Enum Definition
# ---------------------------------------------------------------------------

class MessageRole(str, enum.Enum):
    """
    Role of the message author within a chat session.

    Attributes:
        USER:      A message sent by the authenticated user.
        ASSISTANT: A response generated by the Gemini AI model.
    """

    USER = "USER"
    ASSISTANT = "ASSISTANT"


# ---------------------------------------------------------------------------
# ChatMessage Model
# ---------------------------------------------------------------------------

class ChatMessage(db.Model):
    """
    ORM model representing the ``chat_messages`` table.

    Each row stores one turn of the conversation — either a user prompt
    or an AI response.  Messages are immutable once written.

    Attributes:
        id:         UUID primary key, auto-generated on insert.
        session_id: FK → chat_sessions.id.  Non-nullable; cascades on
                    session deletion.
        role:       ``MessageRole.USER`` or ``MessageRole.ASSISTANT``.
        message:    Raw text content of the message or AI response.
        created_at: UTC timestamp of message creation, set by the database.
                    Used for chronological ordering within a session.

    Relationships:
        session: The parent ``ChatSession`` this message belongs to.
    """

    __tablename__ = "chat_messages"

    # ------------------------------------------------------------------
    # Primary Key
    # ------------------------------------------------------------------

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
        doc="Unique message identifier (UUID v4, auto-generated).",
    )

    # ------------------------------------------------------------------
    # Foreign Key
    # ------------------------------------------------------------------

    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc=(
            "FK to chat_sessions.id.  Non-nullable — every message belongs "
            "to exactly one session.  Cascades deletion when the parent "
            "session is removed."
        ),
    )

    # ------------------------------------------------------------------
    # Message Content
    # ------------------------------------------------------------------

    role: Mapped[MessageRole] = mapped_column(
        String(10),
        nullable=False,
        doc=(
            "Author of the message: 'USER' (human prompt) or "
            "'ASSISTANT' (Gemini AI response).  Stored as VARCHAR(10); "
            "validated against MessageRole at the application layer."
        ),
    )

    message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        doc=(
            "Raw text content of the message.  TEXT with no DB-level length "
            "cap — AI responses can be arbitrarily long; length constraints "
            "are enforced in the Pydantic schema layer."
        ),
    )

    # ------------------------------------------------------------------
    # Timestamp
    # ------------------------------------------------------------------

    created_at: Mapped[DateTime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        doc=(
            "UTC timestamp of message creation, set once by the database "
            "server.  Drives chronological ordering in ChatSession.messages."
        ),
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    session: Mapped["ChatSession"] = relationship(
        "ChatSession",
        back_populates="messages",
        lazy="select",
        doc="The parent chat session this message belongs to.",
    )

    # ------------------------------------------------------------------
    # Representation
    # ------------------------------------------------------------------

    def __repr__(self) -> str:  # pragma: no cover
        preview = self.message[:40] + "..." if len(self.message) > 40 else self.message
        return (
            f"<ChatMessage id={self.id} "
            f"role={self.role!r} "
            f"preview={preview!r}>"
        )
