"""Add AI enrichment fields to Scan

Revision ID: c152802e3c51
Revises: 48dc288d43db
Create Date: 2026-06-25 21:09:20.308626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c152802e3c51'
down_revision = '48dc288d43db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('treatment_plans', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('risk_level')
        batch_op.drop_column('treatment_plans')
        batch_op.drop_column('ai_summary')

    # ### end Alembic commands ###
